@startuml
start

:Iniciar sessão no sistema;

partition CadastroCliente {
  :Inserir dados pessoais;
  :Validar CPF;
  :Calcular idade;
  if () then (Idade <  18)
    :Rejeitar cadastro;
    stop
  else (Idade > 18 ou < 120)
    :Inserir profissão, renda e estado civil;
    :Anexar documentos;
    :Integrar pontuação de crédito;
  endif
}

partition CadastroConta {
  :Selecionar tipo de conta;
  :Gerar número da conta;
  :Vincular cliente;
  :Definir titulares e co-titulares;
  :Inserir data, agência, gerente;
  :Inserir saldo inicial;
  if () then (Saldo < 0)
    :Rejeitar entrada;
    stop
  else (Saldo > 0)
    :Definir nível de serviço;
  endif
}

partition OperacoesFinanceiras {
  :Selecionar operação (depósito, saque, transferência, boleto, PIX);
  :Inserir dados;
  if () then (Valor invalido)
    :Rejeitar operação;
    stop
  else (Valor valido)
    :Se for PIX, validar chaves e limites <<CallBehaviorAction>>;
    :Registrar timestamp e canal;
    :Gerar comprovante;
    :Armazenar histórico;
  endif
}

partition Extratos {
  :Calcular e exibir saldo;
  :Personalizar extrato;
  :Exibir gráficos e categorizar gastos;
  :Exportar extratos(PDF, CSV, OFX);
  :Armazenar extrato por 5 anos;
}

partition Seguranca {
  :Autenticação em dois fatores;
  :Criptografar dados;
  :Registrar logs em acesso;
  :Detectar possiveis fraudes;
  :Bloquear após tentativas de login malsucedidas;
  :Controlar acesso por nível de autorização;
}

:Encerrar sessão;

stop
@enduml